### ISSUE TITLE
JlsException in MakeValid() under decoderstrategy.h

### ISSUE THREAD

**Issue by ramanamohan** [team-charls/charls#1]
Hi All,

First of all I am new to this code, so please pardon me if I am asking some silly query here.

I am getting "_validBits" as 0 in the MakeValid() method under decoderstrategy.h file and this is made as 0 in the "Skip(LONG length)" method, and this is happening only for few images. I would like to understand the reasons behind this behaviour.

Kindly help me get some idea about this and to proceed further on my investigation.

Regards, 
Ramana Mohan

**Comment by vbaderks** [comment]
Hi Ramana,

Just to confirm that you posted your question in the right forum. Could you attach an image that causes  this issue?

Victor

**Comment by vbaderks** [comment]
Closing this issue as not reproducible (did not receive test image).
