### ISSUE TITLE
runtime error: signed integer overflow: -2147483648 - 1 cannot be represented in type 'int'

### ISSUE THREAD

**Issue by malaterre** [team-charls/charls#11]
the code:
https://github.com/team-charls/charls/blob/master/src/encoderstrategy.h#L77

[...]
        if (bitCount < 32)
        {
            int mask = (1 << (bitCount)) - 1;
[...]

does not look quite right for bitCount == 31 ... Maybe use unsigned integer (1u << bitCount)

**Comment by vbaderks** [comment]
Hi malaterre,

From your email I understand that this issue can be closed. 
I looked at the code and did some experimentation with -fsanitize=undefined. The latest C++ v14 docs about left shift state state that it should work on all platforms.
I used your proposal and changed 1 to 1u, this reduces the number of -fsanitize issues.
