### ISSUE TITLE
16 bit grayscale signed, unsigned or both?

### ISSUE THREAD

**Issue by chafey** [team-charls/charls#14]
How does JPEG-LS (and CharLS) handle 16 bit grayscale data signedness?  Does it support both 16 bit signed and unsigned?  If so, how does a caller determine whether the pixel data is signed or unsigned?  If not, is 16 bit grayscale returned as signed or unsigned?  Thanks

**Comment by vbaderks** [comment]
JPEG-LS expects that the input data are unsigned values. If the input data is signed JPEG-LS will threat negative values just as large positive values. As it is a lossless algorithm (when NEAR=0) the same bytes that you put in will be returned when the encoded bitstream is decoded. The info how to interpret the “pixels” is not stored in the JPEG-LS bit stream.

Most image formats define the grayscale format as 0 being black and the max value as white. Almost all image compressions are designed to compress these kind of image efficiently.

DICOM images have a very rich pixel format: MONOCHROME1 vs MONOCHROME2, etc. unsigned vs signed. These attributes always need to be encoded in the DICOM data set. Signed values are mostly used in CT images in which the values are not actually the visible pixels but Hounsfields units. Some processing steps are needed to convert those values in (unsigned) pixels that can be displayed on a computer monitor.

The JPEG-LS algorithm is based on prediction. It predicts the pixel value and then stores the difference with the actual value. For signed values in which many pixel values are around 0 this may cause the prediction to become less effective. I have not tested it myself if applying an offset to the values to make them all positive has a big impact on the compression factor.

**Comment by chafey** [comment]
Thanks for this info, this is really helpful!  The DICOM committee sample data sets for JPEG-LS include 16 bit signed images (the CT images):

ftp://medical.nema.org/MEDICAL/Dicom/DataSets/WG04/compsamples_jpegls.tar

I will use the DICOM header to figure out what the sign is.
