### ISSUE TITLE
error: ‘template<class> class std::auto_ptr’ is deprecated [-Werror=deprecated-declarations]

### ISSUE THREAD

**Issue by malaterre** [team-charls/charls#15]
This is unfortunate but C++11 deprecated `std::auto_ptr`. CharLS codebase should be updated in favor of `std:unique_ptr`. It may be non-trivial to have a portable solution, see: http://programmers.stackexchange.com/questions/291141/how-to-handle-design-changes-for-auto-ptr-deprecation-in-c11

**Comment by vbaderks** [comment]
Hi Mathieu,

Which version of CharLS are you using?.

The 1.x branch targets C++ v03 and uses std:auto_ptr (on purpose). The master branch (v2.0.0) targets C++ v14 and uses std::unique.

Victor

**Comment by malaterre** [comment]
Hi Victor,

Sorry I forgot to check the v2 branch ! Closing this non-sense. Thanks much !
