### ISSUE TITLE
Decoding\Encoding fails on IBM s390x CPU (Big Endian architecture)

### ISSUE THREAD

**Issue by vbaderks** [team-charls/charls#167]

**Comment by malaterre** [comment]
@vbaderks do you want to run some kind of unit test(s) in Debian ? I could not find no equivalent to a simple `make test`.

Currently no tests are being run:

* https://buildd.debian.org/status/fetch.php?pkg=charls&arch=s390x&ver=2.3.1%2Bdfsg-1%2Bb1&stamp=1643219000&raw=0

Thanks

**Comment by vbaderks** [comment]
At the moment all the unit tests are based on the Microsoft unit test framework. There is an open issue (https://github.com/team-charls/charls/issues/52) to convert this to a framework that can run on all platforms. The windows build runs these unit tests.
The tool charlstest, can also execute tests (option -unittest), but is at the moment not connected to (c)make test.
I have interactive access to a s390x VM at the moment, so I can run the tests.

**Comment by vbaderks** [comment]
Resolved with 461df4b0e640726f3a7030a9a79bd5735aa258f4

**Comment by malaterre** [comment]
For reference:

1057bd267a4f4af9a1ced8391571359614da51a2 is the first bad commit
