### ISSUE TITLE
Replace lena8b* image with equivalent non-copyrighted material

### ISSUE THREAD

**Issue by malaterre** [team-charls/charls#175]
Long story short, I cannot upload lena8b* image to Debian archive since it is copyrighted:

* https://lintian.debian.org/tags/license-problem-non-free-img-lenna

Could you please refactor a bit the test suite so that this image is not needed when running `make test`. Maybe something like:

* https://www.tandfonline.com/doi/full/10.1080/09500340.2016.1270881

Of course, I could have #ifdef the code myself, but I wanted to be sure you were aware of the issue yourself.

Thanks for the unit test in 2.3.3

**Comment by malaterre** [comment]
I guess this should work also:

* https://www.itu.int/net/itu-t/sigdb/speimage/Tseries-s.htm

**Comment by malaterre** [comment]
This one as some good alternative:

* https://sipi.usc.edu/database/database.php?volume=misc

> Please note that we no longer distribute the following images that were previously available in our database: 4.2.04 (lena), 4.2.02 (tiffany), elaine.512, numbers.512 and testpat.1k. Although these images have played a significant role in the history of image processing, they no longer represent the best examples for future research.

**Comment by vbaderks** [comment]
Will update/replace test image
