### ISSUE TITLE
charlstest -decodetopnm used inversed UNIX convention

### ISSUE THREAD

**Issue by malaterre** [team-charls/charls#19]
I could provide a simple PR but first I wanted to check why the test uses inverted convention. Eg:
```
$ dd if=/dev/zero of=/tmp/zero.jls count=512
512+0 records in
512+0 records out
262144 bytes (262 kB, 256 KiB) copied, 0.00496284 s, 52.8 MB/s
$ ./charlstest -decodetopnm /tmp/zero.jls tt.pgm
$ echo $?
0
```

On UNIX you need to return a non-zero value to indicate an error.

**Comment by vbaderks** [comment]
charlstest has been started as a quick way to test charls. The main() method has no clear approach which value to return for which case (your probably actually the first to use the return values). I will have a look into that and see if it can be made consistent.
