### ISSUE TITLE
Can anyone provide compiling instructions on linux

### ISSUE THREAD

**Issue by scdeng** [team-charls/charls#2]
I am interested in how jpeg-ls works. how can I build this project on linux? Thanks.

**Comment by vbaderks** [comment]
The following link has the docs how to build CharLS:
https://charls.codeplex.com/wikipage?title=Building%20CharLS&version=3

Note: I have created a todo to copy these instructions to github.

**Comment by vbaderks** [comment]
The building instructions are copied from codeplex to the github wiki.
