### ISSUE TITLE
The Encoding

### ISSUE THREAD

**Issue by Sahil-5111998** [team-charls/charls#229]
Hi,

I am comparing the compression ratio of lossless JPEG in one of my projects. I know that your algorithm follows T.87's order. I went through that doc but could not get which encoding technique is begin used to encode the predicted samples. If possible, please let me know which encoding technique is used by you in this implementation.

**Comment by vbaderks** [comment]
T.87 (ISO  14495-1) only defined 1 encoding/decoding algorithm. This algorithm is also called LOCO-I and was submitted by HP to the JPEG for standardization.
There is a paper "The LOCO-I lossless image compression algorithm: principles and standardization into JPEG-LS" that more clearly explains the ideas behind the algorithm and the steps. 
I hope this answers your question, if not let me know.

**Comment by vbaderks** [comment]
Hi @Sahil-5111998, 

Due to inactivity I am closing this issue. If you still have a question, feel free to re-open it.

**Comment by Sahil-5111998** [comment]
Hi @vbaderks 
Does CharLS has the support for the compression of binary or 1 bit images?
