### ISSUE TITLE
Decoding doesn't work when compiled with mingw64

### ISSUE THREAD

**Issue by xzn** [team-charls/charls#269]
As titled, decoding is broken when compiled with g++ from mingw64, always complaining about invalid encoded data.

Maybe a compiler bug? Not sure what in the myriad of templates triggers it (or something else entirely..)

(clang++ or g++ with ucrt doesn't work either..)

**Comment by vbaderks** [comment]
Thanks for the report. I Will try to reproduce it. On which version of Charls and mingw64 do you see the problem?

**Comment by xzn** [comment]
g++
```
$ g++ --version
g++.exe (Rev5, Built by MSYS2 project) 13.1.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE
```

clang
```
$ clang++ --version
clang version 16.0.2
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: D:/Compilers/msys64/clang64/bin
```


To compile I used `cmake -G "Unix Makefiles"` in either `mingw64` or `clang64` prompt
Then `make charlstest`
Then `make test`
Which fails

My own attempts at using the decoding interface don't work either.

(Also just tried WinLibs MinGW-w64 distribution which has the same problem so it's likely not a problem with my mingw64 installation)

**Comment by xzn** [comment]
I've bisected the problem to commit 0b3ac703e087cca39f4b86a0b7b8bbe7266abd9a

Hope it helps.

**Comment by xzn** [comment]
eh why does g++ generate 32-bit bsr and mask??

![image](https://github.com/team-charls/charls/assets/1617680/13794883-4a66-4e1e-8492-a7899ac9dee5)

This is so weird.

**Comment by xzn** [comment]
I guess this workaround will do for now ...

```c++
template<class T>
auto countl_zero(T value) noexcept -> std::enable_if_t<is_uint_v<64, T>, int>
{
    return countl_zero(static_cast<uint32_t>(value >> 32));
}
```

**Comment by vbaderks** [comment]
commit 36807a0a5c40b3f29ba20d25e0ba78b46874d3a1 resolves this problem in the main branch.
Note: using __builtin_clzll is always possible and is preferable then an extra #ifdef/#else/#endif construction.

Intend is to apply this fix to the v2.4.x branch and research if it is possible to add msys2 to the CI pipeline.

**Comment by vbaderks** [comment]
A fix for this defect has been applied to the release/2.x branch and release v2.4.2 is available.

**Comment by vbaderks** [comment]
The CI pipeline has been extended with MSYS2 to ensure that future releases are automatically verified.
Again, thanks for the report and the fix.
