### ISSUE TITLE
1.x-master does not compile

### ISSUE THREAD

**Issue by marcelvanherk** [team-charls/charls#29]
Hi,

I am trying to use 1.x-master. It lacks several files and therefore does not compile. I miss:

jpegstreamreader.h
jpegmarkercode.h
jpegstreamreader.cpp
jlscodecfactory.h

The versions from the main branch are not compatible.

Thanks,

Marcel

**Comment by vbaderks** [comment]
Hi Marcel,

The 2.x branch and the 1.x branch are not compatible (main reason why major version number was increased). The 1.x branch doesn't have these 4 header files, but the functionality is still there.

The CI server was able to build the last commit:
https://travis-ci.org/team-charls/charls/builds/166053790

Did you do a proper checkout of the 1.x-master branch?

Victor

**Comment by marcelvanherk** [comment]
I will try again tonight.

Marcel

**Comment by marcelvanherk** [comment]
Apologies, I must have made an error. 1.x does compile. I will verify that 1.x causes the same issue with the dicom image I sent.

Marcel

**Comment by marcelvanherk** [comment]
My silly error is that I failed to include header.c in the build...
