### ISSUE TITLE
Incorrect assignment in colortransform.h?

### ISSUE THREAD

**Issue by anders9ustafsson** [team-charls/charls#31]
When browsing the code, I found the following questionable (?) assignment in [colortransform.h, line 120](https://github.com/team-charls/charls/blob/master/src/colortransform.h#L120)

    hp3.v1 = SAMPLE(G + ((hp3.v2 + hp3.v3)>>2)) - RANGE / 4;

I might be mistaken, but shouldn't the last right parenthesis be placed at the end of the assignment, i.e.

    hp3.v1 = SAMPLE(G + ((hp3.v2 + hp3.v3)>>2) - RANGE / 4);

**Comment by vbaderks** [comment]
Thanks for the report, your are probably right. I will add a unit test for it.

**Comment by vbaderks** [comment]
I added an unit test, both option return the same result for the whole uint8_t range.
