### ISSUE TITLE
Error while decoding 

### ISSUE THREAD

**Issue by AswaniV** [team-charls/charls#319]
I'm using CharLSDecodeRaster to decode the encoded jpegLS buffer to a raster and it is failing with error code 5. In the raster retuned height,width,pixcel format seems to be 0. Please help in understanding what is error code 5 indicates and what could be the reason leading to this.

[DecodeParams.json](https://github.com/user-attachments/files/16675264/DecodeParams.json)

**Comment by vbaderks** [comment]
Hard to tell, I am not familiar with the method CharLSDecodeRaster or the context in which you are calling this method. All error codes of CharLS can be found in the file public_types.h. For example: https://github.com/team-charls/charls/blob/release/2.x/include/charls/public_types.h

Error code 5 = CHARLS_JPEGLS_ERRC_INVALID_ENCODED_DATA
