### ISSUE TITLE
Support for c++11

### ISSUE THREAD

**Issue by malaterre** [team-charls/charls#38]
As far as I understand the only requirement for c++11 is `std::make_unique`. Would you consider accepting a pull request which does:

```
$ cat src/util.h 
[...]
#if __cplusplus == 201103L
template<typename T, typename... Args>
std::unique_ptr<T> make_unique(Args&&... args)
{
    return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
}
#endif

```

**Comment by vbaderks** [comment]
Hi Mathieu,

Yes, it would not be a problem to add such a template to util.h to provide backwards compatibility for building CharLS with a C++11 compiler.

You might take the following things in consideration:
- The current CI environments are testing CharLS in C++14 mode with MSVC, GCC and clang. An additional CI environment would need to be created to test CharLS in C++11 mode.
- I already created a develop git branch a couple of months ago as preparation for CharLS 3.x. CharLS 3.x will target C++17 (allowing usage of constexpr). The current master branch will be maintained as 2.x-master and stay on C++14 (and with your patch on C++11) forever. There is currently no timeline when the 3.x release is good enough to make the switch.
- The construction __cplusplus == 201103L might be too simple for all currently supported compilers, MSVC is for example not very reliable in updating this number. And many compilers provide a switch to select the C++ standard. It may be required to also update the CMakeLists.txt file to provide a reliable way to switch this compatibility mode on.

Victor

**Comment by vbaderks** [comment]
Hi Mathieu,

Is this request still relevant or is the need to support C++11 not needed anymore?

Victor

**Comment by vbaderks** [comment]
Hi Mathieu,

I have updated the support policy of CharLS. The main policy is now based on google's "Live at head". A C++ standard is now supported for 3 years, from the moment a new C++ standard is published. Given the fact that C++14 has been published in 2014-12-15, C++11 is not supported anymore.

Victor

Note: as C++17 has been published on 2017-12, support for C++14 will end in 2020-12.
