### ISSUE TITLE
Compressed output size is larger than the raw data

### ISSUE THREAD

**Issue by sjose16** [team-charls/charls#40]
I have a raw image that I'm trying to compress using the library.  My input data size is 57658368 and after calling JpegLsEncode, the bytesWritten output is 59951222.  Any idea why the compressed length is larger than raw size?

JlsParameters params = JlsParameters();
 params.width = 6576;
 params.height = 4384;
 params.bitsPerSample = 16;
 params.stride = 0;
 params.components = 1;
 params.interleaveMode = InterleaveMode::None;
 params.colorTransformation = ColorTransformation::None;

**Comment by vbaderks** [comment]
It is very rare that an image becomes larger. Normally this only happens with special created "white noise" images, that are part of the test suite.
What happens if you try compress your image with for example PNG?

**Comment by vbaderks** [comment]
Hi sjose16,

I am closing this question for now, feel free to re-open it when needed.

Victor
