### ISSUE TITLE
Add support for lossy comperssion

### ISSUE THREAD

**Issue by urimerhav** [team-charls/charls#43]
Looks like the code only supports lossless compression, or at least that's what I understand from going over `convert.c`. Any chance we can add lossy compression, or add example code that calls a lossy compression?

**Comment by vbaderks** [comment]
Hi Uri,

JPEG-LS supports both lossless and near-lossless. The JPEG-LS standards defines near-lossless as:

**near-lossless:** A description term for lossy encoding and decoding processes and procedures in which the output of the decoding process is such that each reconstructed image sample differs from the corresponding one in the input to the encoding process by not more than a pre-specified value.

This is different then 'normal' JPEG for which you would specify a quality parameter, but have no actual control on error range.

The current implementation supports both. I have updated the sample to demonstrate that functionality.

**Comment by vbaderks** [comment]
Hi Uri,

I didn't receive anymore questions about this topic. If you have more questions about it in the future, you are welcome to re-open this issue/question.
