### ISSUE TITLE
Add support for gcc visibility stuff

### ISSUE THREAD

**Issue by malaterre** [team-charls/charls#44]
Here is one patch that we maintain within Debian:

https://salsa.debian.org/med-team/charls/blob/master/debian/patches/add_visibility.patch

Would be nice to handle upstream directly. Thanks

**Comment by vbaderks** [comment]
Hi,

With commit 6fdf0893ba0fa50d6357b48f16269ce4b0742fe6 the file api_abi.h was added. This file introduces the macro:

`CHARLS_API_IMPORT_EXPORT __attribute__((visibility("default")))`

when the build target is a shared library for Linux.

**Comment by vbaderks** [comment]
Hi @malaterre,

I assume that the provided solution works for your problem, if not please let me know.
