### ISSUE TITLE
Remove STL exported symbol

### ISSUE THREAD

**Issue by malaterre** [team-charls/charls#45]
Here is another patch from Debian that we maintain: hiding of STL stuff being automagically exported. Here is the hack that I wrote long ago:

https://salsa.debian.org/med-team/charls/blob/master/debian/patches/stl_symbols_hack.patch

Would be nice to handle gracefully using some portable cmake magic.

**Comment by malaterre** [comment]
FYI, this depends on #44

**Comment by vbaderks** [comment]
Added:

`set_target_properties(charls PROPERTIES CXX_VISIBILITY_PRESET hidden)`

to the CMakefile.txt for the charls library project. (3925d572168bba4b5cfc249727a2e56a77a2fb07)

**Comment by vbaderks** [comment]
Hi @malaterre,

I assume that the provided solution works for your problem, if not please let me know.
