### ISSUE TITLE
No rule to make target 'test'

### ISSUE THREAD

**Issue by hubutui** [team-charls/charls#49]
Hey, I notice that `BUILD_TESTING:BOOL=ON` by default. But, it seems that there is no rule to make target 'test', so how could I run test after compiling charls? I'm trying to create a package for ArchLinux.

**Comment by vbaderks** [comment]
Hi,

Is this question about release 2.0.0 or about the latest version on the master branch.
The CMake scripts have been updated to "modern" CMake on the  master branch

**Comment by hubutui** [comment]
@vbaderks Hi, it's the release 2.0.0. I run cmake:
```shell
cmake \
    -DCMAKE_INSTALL_PREFIX:PATH=/usr \
    -DCMAKE_BUILD_TYPE:STRING=Release \
    -DBUILD_SHARED_LIBS:BOOL=ON
```
and then
```shell
make test
```
I check with `make help`, and found a `charlstest` target. It seems that `make charlstest` just compiles and builds a file `charlstest`? So I could run the test with:
```shell
./charlstest -unittest -dontwait
```
I'm not sure if `-unittest` covers all the unit test needed.

**Comment by vbaderks** [comment]
./charlstest -unittest -dontwait will execute all cross platform tests that are available.

Note:
There is also a (Windows only) Visual Studio project that has some more low level tests. As these tests are based on the Visual Studio C++ unit test framework they are not cross platform. Going forwards the intend is to replace this unit test framework with a cross platform C++ unit test framework in the future.

**Comment by hubutui** [comment]
OK, thank you. Now charls is available in ArchLinuxCN repo https://github.com/archlinuxcn/repo.
