### ISSUE TITLE
util.h is not installed

### ISSUE THREAD

**Issue by hubutui** [team-charls/charls#50]
It seems that the `util.h` is not installed in the final `make install` step. Should it be installed? I'm trying to package gdcm with system's charls, and it complains that `CharLS/util.h` not found.

**Comment by vbaderks** [comment]
Hi hubutui,

Which version are you trying to install? 
util.h is needed to build the library\DLL, but not part of the public API.

**Comment by hubutui** [comment]
I have charls 2.0.0 installed. I compiled charls using this [PKGBUILD](https://github.com/archlinuxcn/repo/blob/53ba7086c59678fbf765194602129457dd5d5e4b/archlinuxcn/charls/PKGBUILD) in a archroot environment. The final installation tree looks like this:
```text
usr
├── include
│   └── CharLS
│       ├── charls.h
│       └── publictypes.h
├── lib
│   ├── libCharLS.so -> libCharLS.so.2
│   ├── libCharLS.so.2 -> libCharLS.so.2.0
│   └── libCharLS.so.2.0
└── share
    └── licenses
        └── charls
            └── LICENSE
```
The complete build log: [log.txt](https://github.com/team-charls/charls/files/3342902/log.txt)

**Comment by vbaderks** [comment]
That installation tree looks fine to me. 

The error I see in log.txt is:
charls E: Dependency gcc-libs detected and not included (libraries ['usr/lib/libstdc++.so.6', 'usr/lib/libgcc_s.so.1'] needed in files ['usr/lib/libCharLS.so.2.0'])

Your are building with -DBUILD_SHARED_LIBS:BOOL=ON. I have no experience with PKGBUILD, but when building a shared library charls also depends on the shared versions of the C++ and C runtime libraries.

Is the PKGBUILD file missing a dependecy?

**Comment by hubutui** [comment]
Thank you, so since `utils.h` is not part of the public API, one should not include this header.

As for the missing `libgcc_s.so`, I would add the `gcc-libs` to  deps.

**Comment by hubutui** [comment]
gdcm upstream has soloved this issue. It's a issue of gdcm upstream. Thanks for you help.
