### ISSUE TITLE
Assert hit while loading possibly invalid data

### ISSUE THREAD

**Issue by yvoronov-artec** [team-charls/charls#53]
Hello,

It seems like there is a problem in checking validity of data. The function stack is as follows:
```
-- ReadHighBits()
-- -- ReadBit()
-- -- -- MakeValid()
```
The matter is that in function MakeValid() the assert has a hit here - 
`ASSERT(static_cast<size_t>(validBits_) <=bufType_bit_count - 8);`
It occures when `validBits_` is negative - it happened in `ReadHighBits()` when `Skip(15)` is called. 

Am I right that `validBits_` is not supposed to be negative? Then the check `if (validBits_ <= 0)` in ReadBit() should be fixed in a way of throwing an exception when `validBits_ < 0`.

**Comment by yvoronov-artec** [comment]
Seems like the same problem as in #37.

**Comment by vbaderks** [comment]
I looked into #37, but the repro there, won't cause the assert as the latest code on the master branch has been extended with extra validation steps.

Do you have a repro that demonstrates your problem?

**Comment by yvoronov-artec** [comment]
Sorry for delay, it takes some time to rebuild my system with master.

Yes, I do have a reproduction with the newest code. However, my data example is about 1Mb in size, and I am not quite sure how to share it here. Any ideas?

**Comment by vbaderks** [comment]
I think github allows attachments to be added to issues, not sure what the size limitation is. As an alternative you can also send it directly to my private email.

**Comment by yvoronov-artec** [comment]
Ok, I managed to add data to the issue. And here is the code:
```
    auto params = JlsParameters();
    auto inputInfo = FromByteArrayConst(input.data(), input.size());
    error = JpegLsReadHeaderStream(inputInfo, &params);
    if(error == charls::jpegls_errc::OK)
    {
        const int bytesPerSample = params.bitsPerSample > 8 ? 2 : 1;
        Buffer outputBuffer(params.width * params.height * bytesPerSample * params.components);

        const auto outputInfo = castBuffer(outputBuffer);
        error = JpegLsDecodeStream(outputInfo, inputInfo, &params);
```
Here comes the ASSERT in decoder_strategy.h:130, in the function MakeValid()

The file [dumpdata.zip](https://github.com/team-charls/charls/files/3685978/dumpdata.zip) - contains two files, `dumpdata.bin` - actual _input_ data, and `dumpdata.txt` - some Jls Parameters printed.

Thanks,
Yury

**Comment by vbaderks** [comment]
Thanks for the data. Will try to look into it when I can reserve some free time.
