### ISSUE TITLE
ModuloRange implementation issue 

### ISSUE THREAD

**Issue by Czaki** [team-charls/charls#54]
I meet this problem on release 2.0.0
In the function `ModuloRange` from file `src/default_traits.h` there are two inconsistencies 
```c++
FORCE_INLINE int32_t ModuloRange(int32_t errorValue) const noexcept
    {
        ASSERT(std::abs(errorValue) <= RANGE);

        if (errorValue < 0)
        {
            errorValue += RANGE;
        }
        if (errorValue >= (RANGE + 1) / 2)
        {
            errorValue -= RANGE;
        }

        ASSERT(-RANGE / 2 <= errorValue && errorValue <= static_cast<int32_t>(ceil(static_cast<double>(RANGE) / 2)) - 1);
        return errorValue;
    }
```
why here is 
```c++
if (errorValue < 0)
        {
            errorValue += RANGE;
        }
```
and not 
```c++
if (errorValue < -RANGE / 2)
        {
            errorValue += RANGE;
        }
``` 
And rounding rules creates problem with eg. `RANGE=25` and `errorValue=12` The rounding rule do not apply, but end assertion aplly, so code ends with faliture. My suggestion for fixes is:
```c++
FORCE_INLINE int32_t ModuloRange(int32_t errorValue) const noexcept
    {
        ASSERT(std::abs(errorValue) <= RANGE);

        if (errorValue < -RANGE / 2)
        {
            errorValue += RANGE;
        }
        if (errorValue >= (RANGE + 1) / 2)
        {
            errorValue -= RANGE;
        }

        ASSERT(-RANGE / 2 <= errorValue && errorValue <= RANGE - (RANGE) / 2 - 1);
        return errorValue;
    }
```
But I`m not sure how it should work, so I open issue, not pull request. I can open pull request if you ask for it.

**Comment by vbaderks** [comment]
Thanks for the report. I will look into it. The current code is a direct copy of the JPEG-LS specification document (section ITU.T.87, A.4.5 (code segment A.9).

**Comment by Czaki** [comment]
i see. My bad in firs error. It looks like I read second if as elif. 

current code looks correct but still in release 2.0.0 there is problem with no ceil. There is possibility of fix it in something like 2.0.1?

here is my suggestion of fix. 
```c++
    inlinehint int32_t ModuloRange(int32_t errorValue) const
    {
        ASSERT(std::abs(errorValue) <= RANGE);

        if (errorValue < 0)
        {
            errorValue += RANGE;
        }
        if (errorValue >= (RANGE + 1) / 2)
        {
            errorValue -= RANGE;
        }

        ASSERT(-RANGE / 2 <= errorValue && errorValue <=  ((RANGE+1) / 2)-1);
        return errorValue;
    }

```

**Comment by vbaderks** [comment]
The ASSERT is fixed in the current master branch. I think your ASSERT is simpler, will replace 

`ASSERT(-RANGE / 2 <= errorValue && errorValue <= static_cast<int32_t>(ceil(static_cast<double>(RANGE) / 2)) - 1);`

with

`ASSERT(-RANGE / 2 <= errorValue && errorValue <=  ((RANGE + 1) / 2) - 1);`

The next version will be 2.1.0-rc1 and then 2.1.0.

**Comment by Czaki** [comment]
Thanks. So temporary I will patch library in my project, since next release.
