### ISSUE TITLE
Check library version at compile or runtime

### ISSUE THREAD

**Issue by cgohlke** [team-charls/charls#56]
Hello. Thank you for developing the CharLS library! I use it from Python via Cython. 

I cannot seem to find a way to check the CharLS library version at compile or runtime.

Would it be possible to add some defines and/or functions to the API? For example

```C
#define CHARLS_VERSION_MAJOR    2
#define CHARLS_VERSION_MINOR    1
#define CHARLS_VERSION_RELEASE  0
#define CHARLS_VERSION_NUMBER  (CHARLS_VERSION_MAJOR * 100*100 + CHARLS_VERSION_MINOR * 100 + CHARLS_VERSION_RELEASE)

CHARLS_API_IMPORT_EXPORT const char* CHARLS_API_CALLING_CONVENTION charls_get_version_string(void);
CHARLS_API_IMPORT_EXPORT const uint32_t CHARLS_API_CALLING_CONVENTION charls_get_version_number(void);
```

**Comment by vbaderks** [comment]
Hi,

Some questions:
- What would be the typical use case to check version numbers?
- Is it important to have #define(s) or are constexpr numbers also ok?

My preference would be to use semver names and only provide the 3 semver parts:

```
#define CHARLS_VERSION_MAJOR    2
#define CHARLS_VERSION_MINOR    1
#define CHARLS_VERSION_PATCH    0

CHARLS_API_IMPORT_EXPORT const char* CHARLS_API_CALLING_CONVENTION charls_get_version_string(void);
CHARLS_API_IMPORT_EXPORT charls_jpegls_errc CHARLS_API_CALLING_CONVENTION charls_get_version_number(int32_t* major, int32_t* minor, int32_t* patch);
```
This would allow to check for breaking changes, and the user of CharLS can merge the numbers in the format he needs.

The version string that would be returned would look like "2.1.0" (offical release), "2.1.0-rc1", "2.2.0-alpha1", etc.

**Comment by cgohlke** [comment]
> What would be the typical use case to check version numbers?

I would like to (1) provide the CharLS version information at runtime to the user of my software and (2) control conditional compilation via the C preprocessor.

> Is it important to have #define(s) or are constexpr numbers also ok?

I think it has to be #define(s) for the preprocessor.

> My preference would be to use semver names and only provide the 3 semver parts:

> This would allow to check for breaking changes, and the user of CharLS can merge the numbers in the format he needs.

> The version string that would be returned would look like "2.1.0" (offical release), "2.1.0-rc1", "2.2.0-alpha1", etc.

That would be perfect!

**Comment by cgohlke** [comment]
Thank you!
