### ISSUE TITLE
JpegLsReadHeader() does not set JlsParameters.stride

### ISSUE THREAD

**Issue by chafey** [team-charls/charls#68]
JlsParameters.stride is always zero when calling JpegLsReadHeader().  This used to work in the past, but no longer does.  I can submit a PR for this if you want it fixed, but may not be worth it since it is being deprecated

**Comment by vbaderks** [comment]
Are you using the stride value returned from JpegLsReadHeader for something special?

When passing a stride of 0 to JpegLsDecode, the library will compute the stride value. The same as used to be returned by JpegLsReadHeader in 2.0

This API is deprecated but still maintained until it will be removed in next major release. PR are welcome.

**Comment by chafey** [comment]
No special reason, I just had some old code that used it to find the beginning of each vertical line in a decoded image.  I seem to recall thinking I should use stride just in case charls decided to pad the image width for some reason (e.g. odd width image?).

**Comment by vbaderks** [comment]
CharLS will by default compute a stride that uses no padding. It is up to the caller to set a specific stride for the uncompressed output buffer if he knows such a stride is a requirement for being able to display the image.
For example some legacy Windows display functions require that every scan line starts at a 32-bit address.

In the new API, stride is a parameter of the decode function, and together with the destination_buffer and the size of the buffer are a logical unit.
