### ISSUE TITLE
Support for reading regions

### ISSUE THREAD

**Issue by HGuillemet** [team-charls/charls#72]
Decoding a specific ROI seems not supported anymore with the new 2.1.0 API.
Could you consider adding it back ?

**Comment by vbaderks** [comment]
Technically this would be possible.
What would be the typical use case to have this ROI feature? 
Internally the decoder needs most of the times to decode the complete image before it can apply the ROI "filter".

**Comment by vbaderks** [comment]
Hi @HGuillemet, as I didn't get an answer about what would be the typical use case, I am unable to process this request. 

Feel free to re-open this issue when you have more information.
