### ISSUE TITLE
Documentation on pixel data input and output format can be misinterpreted

### ISSUE THREAD

**Issue by keanergr** [team-charls/charls#74]
We are very happy with the quality of the library and will be using it for our products to implement JPEG-LS in medical imaging environments.  This is a minor documentation issue, but I thought it would be helpful to fix the section in "How to use the API" where the expected format for an RGB image is described as:

interleave mode | format
--- | ---
none | RRRRGGGGBBBB
line | RGBRGBRGBRGB
sample | RGBRGBRGBRGB

Note that the definition for line interleaved is the same as sample.  If you used more pixels and had another column for annotations it might be clearer how line and sample are different.  For example, identify this as a 3 row by 4 column image and then:

interleave mode | format | notes
--- | --- | ---
none     | RRRRRRRRRRRR | red plane
"            | GGGGGGGGGGGG | green plane
"            | BBBBBBBBBBBB | blue plane
line        | RRRRGGGGBBBB | row 1
"            | RRRRGGGGBBBB | row 2
"            | RRRRGGGGBBBB | row 3
sample  | RGBRGBRGBRGB | row 1
"            | RGBRGBRGBRGB | row 2
"            | RGBRGBRGBRGB | row 3

I apologize that I am not skilled at markdown; hopefully my attempt at a table is understandable.  Of course it is possible that my understanding is also not correct.

Best regards,
Roger Keane

**Comment by vbaderks** [comment]
Hi @keanergr,

Thanks for the feedback. I think your proposal makes sense to improve the current documentation. 

Be aware however that the input buffer and output buffer of the "line" option and the "sample" option are **identical**. The generated JPEG-LS encoded bit-stream is different interleaved, but not the format of the input and output buffers.

Using the "none" option is actually the recommended option as is faster to encode and decode and generates better compressed images. It does requires however an additional pre/post step as "by-pixel" is often the required display format.

**Comment by keanergr** [comment]
Hi @vbaderks,
Your explanation that the input and output buffers are identical for the "line" and "sample" options clears up the confusion that we were having.  I understand why "none" is faster and generates better compressed images.  I also assume that "line" is faster and generates better compressed images than "sample", which is likely why we see that used in the few color datasets we have as samples.

Thank you for your response and for your contributions,
Roger Keane

**Comment by vbaderks** [comment]
Note: "sample" compresses also less due to restrictions set by the JPEG-LS standard (B.3.1.) , which only allow the encoder to enter run mode when this can be done for all components.
