### ISSUE TITLE
struct charls_jpegls_decoder constructor no default attribute

### ISSUE THREAD

**Issue by messicn** [team-charls/charls#78]
struct charls_jpegls_decoder {

charls_jpegls_decoder() = default;

**Comment by vbaderks** [comment]
Thanks for the report. There was actually no need to define the defaulted constructor in the charls_jpegls_encoder class. Fixed with 07fea56bed507f59692a4c13768d031a398c1bc8

**Comment by messicn** [comment]
Your work is great!
