### ISSUE TITLE
Do you support the specification ITU-t81?

### ISSUE THREAD

**Issue by egorsh0** [team-charls/charls#8]

**Comment by vbaderks** [comment]
Hi egorsh0,

CharLS implements ISO/IEC 14495-1:1999 | ITU-T Rec. T.87 (1998). T.87 describes the JPEG-LS algorithm. T.87 references the ISO/IEC 10918-1 | ITU-T Recommendation T.81 standard and a lot of concepts are shared between the 2 standards. T.87 and T.81 are however different algorithms. T.81 is the standard for the "common" lossy JPEG and lossless JPEG algorithms. A good overview can be found at jpeg.org.

A open source reference implementation of T.81 can be found at https://github.com/thorfdbg/libjpeg

Victor
