### ISSUE TITLE
Default preset coding parameters not computed for unset values

### ISSUE THREAD

**Issue by planetmarshall** [team-charls/charls#84]
Default values for preset coding parameters are only calculated if **all** the parameters are set to zero.

From Annexe 3 in the spec:

> For MAXVAL, T1, T2, T3 and RESET, a value of 0 indicates reverting to default values as given in Table C.2.

This behaviour actually causes conformance tests 9 and 10 to fail if compression behaviour is verified (the existing tests read the compression parameters from the header of the compressed images rather than setting them explicitly), as you have to set either **all** of the parameters or **none** of them.

Test 10 (t1=t2=t3=9, reset=31) will assert in `compute_default` because `maximum_sample_value` will be `0`.

Will try and come up with a reproducible example, and possibly a patch if I have time.

**Comment by vbaderks** [comment]
A  reproducible example would be very helpful.
