### ISSUE TITLE
Writing multiple frames overflows destination buffer - how to reset?

### ISSUE THREAD

**Issue by timmyd7777** [team-charls/charls#86]
Hi all.  I am using CharLS in C++ to write multiple frames to the same destination buffer.  Frames are all 1920x1080, 8-bit, monochrome; they happen to be video frames coming in from a B/W webcam.  I am writing them in a loop like this:

    jpegls_encoder encoder;
    frame_info info = { 1920, 1080, 8, 1 };
    size_t buffer_size = 1920 * 1080; // encoder.estimated_destination_size();
    char *buffer = new char[ estimated_destination_size ];
    encoder.destination ( buffer, buffer_size );

    while ( /* video frames are coming in from camera */ )
    {
         size_t bytes_written = encoder.encode ( video_frame.pixelptr, video_frame.width * video_frame.height );
         if ( bytes_written )
              /* write contents of buffer to file */
    }

This works fine for the first few frames.  But eventually I get an exception thown, with the error message "The destination buffer is too small to hold all the output".

It looks like the encoder is writing each new frame after the end of the frames it has already written; it must be updating its internal copy of the destination buffer.  But, as far as I can tell, there is no way to "rewind" or "reset" the destination buffer after frames have been written.  If I call encoder.destination() after the frame has been written, I get an "invalid operation" exception.

Is there some way to re-use the same destination buffer each time I want to compress an individual video frame?  It seems very wasteful to have to do all the encoder setup each time through the loop.  If this is not currently possible, can I ask for this addition as a feature request?

Thanks.

**Comment by vbaderks** [comment]
Currently it is not possible.
I can add a "rewind" function. The function name "reset" may indicate that all properties are reset to their default values, but I think you only want the buffer pointer and the state of the encoder back to the beginning.

**Comment by timmyd7777** [comment]
OK, thanks.  encoder.rewind() would be great.  Appreciate the fast feedback.

**Comment by vbaderks** [comment]
Solved by c8904021b3f0db509675b2f620051d81a9fec965
