### ISSUE TITLE
Global visibility of variables causes seg faults in certain cases

### ISSUE THREAD

**Issue by gregsharp** [team-charls/charls#87]
My program links to both ITK and dcmtk on Fedora 33. ITK is built from source whereas dcmtk is supplied by the OS package manager. This causes a crash at exit due to a double free of static variables within CharLS. Specifically it is these variables:

vector<signed char> rgquant8Ll = CreateQLutLossless(8);
vector<signed char> rgquant10Ll = CreateQLutLossless(10);
vector<signed char> rgquant12Ll = CreateQLutLossless(12);
vector<signed char> rgquant16Ll = CreateQLutLossless(16);

At program exit, ITK's static CharLS frees them, and then the dynamically linked CharLS frees them again causing a segmentation violation.

Could these be made internal to the shared library, e.g. by changing the visibility attribute?

**Comment by vbaderks** [comment]
In CharLS v2.1.0 and newer versions all symbols on Linux are hidden except the public API methods.

**Comment by gregsharp** [comment]
That is great news.  Thank you!
