### ISSUE TITLE
Feature request: Provide 'jpegtran' equivalent for JPEG-LS

### ISSUE THREAD

**Issue by malaterre** [team-charls/charls#89]
jpegtran is a well known command line tool for ITU 81 JPEG files. It allows one to do simple transpose/crop/flip/rotate by 90° increments a lossy compress JPEG.

It would nice to expose this also for JPEG-LS, since otherwise it requires full decompression of the input image (which is not desirable for lossy JPEG-LS).

**Comment by malaterre** [comment]
Technically modern version of jpegtran also supports 'wipe' (opposite of crop), which is also kind of neat.

**Comment by vbaderks** [comment]
jpegtran uses a clever technique to rotate jpeg images lossless by operating on the DCT blocks.
JPEG-LS does not operate using DCT blocks, but on scan lines. I think the only way to rotate a JPEG-LS image is by first always decode it, rotate and then encode. For lossless this is of course only a performance problem, for near-lossless it may indeed introduce an additional error.

It may still be beneficial for users to have a tool like "jpeglstran" that offers the same functionality.

**Comment by malaterre** [comment]
@vbaderks Technically this feature request could be implemented with a simple header patch API, right ?

Steps:

1. Read near-lossless `input.jls` and keep JPEG-LS header (in particular: max deviation value is -say- '2')
2. Decompress `input.jls` as `output.pgm` (for example)
3. Rotate 90° PGM (lossless), as `rot90.pgm`
4. Compress `rot90.pgm` as `rot90.jls` (max deviation = 0, lossless encoder)
5. Patch header `rot90.jls` to set max deviation to original value (eg. '2'), so it now appears as near-lossless.

Would that work ?

**Comment by vbaderks** [comment]
I think that approach might work. I would ensure that the max. deviation value, relative to the original is not larger than 2.
Would have to check if there is some decoding dependency when changing the near-lossless value in the header only.

**Comment by vbaderks** [comment]
@malaterre You mentioned in that you might be working on a tool like 'jpegtran' for JPEG-LS. Do you have URL of a public repro?

Otherwise I could create a new repro and close this issue by forwarding to it. I expected that initially there will be a different release-lifetime between the tool and the CharLS library.
