### ISSUE TITLE
EncoderStrategy::AppendToBitStream method fails if buffer is full, 31 bits are added and xFF bytes are written

### ISSUE THREAD

**Issue by vbaderks** [team-charls/charls#9]
Note: this is an issue originally reported on codeplex: http://charls.codeplex.com/workitem/10742

Hi, 
  
we received a bug report for the copy of CharLS that is part of the DCMTK: 
http://forum.dcmtk.org/viewtopic.php?f=1&t=3412 
  
I took a look at this file and I think that this is indeed a bug in CharLS. 
  
The attached patch creates an EncoderStrategy instance and writes bits to it. This triggers the same assertion as the original test image. (Ignore my changes to encoderstrategy.h, that's just the debug output that I looked at for figuring this out): 
  
encoderstrategy.h:95: void EncoderStrategy::AppendToBitStream(LONG, LONG): Assertion `bitpos >=0' failed. 
  
My analsysis of what is going on is part of the patch, so be sure to read the comments. :-) 
  
I tried to come up with a patch that fixes this. This is the following part of the diff: 
 
if (bitpos >= 0)
if (bitpos > 0) 
  
The idea here is that when 32 bits of input were read, we can Flush(). 
  
This should even fix a similar issue, where we have bitpos == 1 and add 31 input bits, so one bit gets added to valcurrent. If Flush() only writes out 30 bits, all the 30 bits of input left can go into the buffer. 
  
Cheers, 
Uli

**Comment by vbaderks** [comment]
Some more background info and a pgm sample file that demonstrates the problem can found at:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816607

**Comment by mattbrynne** [comment]
BUY REAL QUALITY PASSPORTS,VISAS,DRIVER LICENSE,GREEN CARDS,IDs
We offer only original high-quality fake passports, driving licenses, identity cards, visas, birth certificates
And other products for a number of countries such as:
USA, Australia, Belgium, Brazil, Canada, Finland, France, Germany, Israel, Mexico, Netherlands, South
Africa, Spain, Great Britain etc.
To get the additional information and order the order, visit our website:
(If you are not able to visit our website for technical reasons, we are looking forward to your request
Questions about the e-mail addresses listed below)

Website======  http://legitdocs4all.com

Contact by e-mail=========: mattbrynne002@gmail.com


General support:=== mattbrynne002@gmail.com

WHATSAPP NUMBER ===== +1(317)210 1175


-IDs Scan-yes ...
-HOLOGRAMES: IDENTICAL
-BARCODES: IDS SCAN
-UV: YES
FAKE IDS WITH FAST SHIPPING - EMAIL SUPPORT
Buy real USA (USA) passports,
Buy genuine Australian passports,
Buy genuine Belgium passports,
Buy real Brazilian (Brazil) passports,
Buy genuine Canadian (Canada) passports,
Buy genuine Finnish (Finland) passports,
Buy realFrench (France) passports,
Buy real German (Germany) passports,
Buy fake Dutch (Netherlands / Holland) Passports,
Buy fake Israel passports,
Buy fake UK (United Kingdom) Passports,
Buy fake Spanish (Spain) passports,
Buy false diplomatic passports,
Buy Camouflage Passports,
Buy Pass duplicates,
Real United States Passports on sale,
Real Australian passports for sale,
Real Belgium passports for sale,
Genuine Brazilian (Brazil) passports for sale,
Real Canadian (Canada) passports for sale,
Genuine Finnish (Finland) passports for sale,
Genuine French (France) passports for sale,
Real German (Germany) passports for sale,

General  support========: mattbrynne002@gmail.com

WHATSAPP NUMBER ===== +1(317)210 1175

Website =====    http://legitdocs4all.com


BUY HIGH QUALITY REAL / FAKE PASSPORTS, DRIVER LICENSE, ID CARDS, US ITUNES CARDS, BANKS, etc.
Buy Real / Fake Passports, Driving Licenses, ID Cards, Visa, USA Green Card, Citizenship, US itunes cards.
